{
 "title": "GrafaWatt dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Production d'électricité par filière en France",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"origin-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eco2mix_national_measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bioenergies\" or r[\"_field\"] == \"coal\" or r[\"_field\"] == \"fuel_oil\" or r[\"_field\"] == \"gas\" or r[\"_field\"] == \"hydro\" or r[\"_field\"] == \"nuclear\" or r[\"_field\"] == \"solar\" or r[\"_field\"] == \"wind\")"
    }
   ]
  },
  {
   "title": "Émissions de CO2 / kWh produit en France",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gCO2eq/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"origin-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eco2mix_national_measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")"
    }
   ]
  },
  {
   "title": "Consommation nationale",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"origin-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eco2mix_national_measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")"
    }
   ]
  }
 ]
}