apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    editable: false
    url: ${GF_INFLUXDB_URL}
    user: ${GF_INFLUXDB_USERNAME}
    password: ${GF_INFLUXDB_PASSWORD}
    jsonData:
      version: Flux
      organization: ${GF_INFLUXDB_ORG}
      defaultBucket: ${GF_INFLUXDB_BUCKET}
    secureJsonData:
      token: ${GF_INFLUXDB_TOKEN}